server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Face
    username: ${DB_NAME}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  jwt:
    key: ${JWT_SC}
    access: ${JWT_AT}
    refresh: ${JWT_RT}


logging:
  level:
    org:
      hibernate:
        type: trace