server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: ${DB_NAME}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  jwt:
    key: ${JWT_SC}
    access: ${JWT_AT}
    refresh: ${JWT_RT}

cloud:
  aws:
    s3:
      default-image: https://s3.ap-northeast-2.amazonaws.com/face.s3/KakaoTalk_Photo_2023-11-30-19-41-06.png
      url: http://face.s3.s3-website.ap-northeast-2.amazonaws.com
      bucket: face.s3
    credentials:
      access-key: AKIASLBWSW4ICNOGH3XX
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      hibernate:
        type: trace